// Generated by ts-to-zod
import { z } from "zod";

export const healthCheckResSchema = z.object({
  status: z.union([z.literal("ok"), z.literal("error")]),
  timestamp: z.string(),
  version: z.string(),
});

export const testCaseProjectsResSchema = z.object({
  projects: z.array(
    z.object({
      id: z.string(),
      key: z.string(),
      name: z.string().optional(),
    }),
  ),
});

export const appSettingsResSchema = z.object({
  settings: z.object({
    testCaseProjects: z
      .array(
        z.record(z.unknown()).and(
          z.object({
            id: z.string(),
            key: z.string(),
            name: z.string().optional(),
          }),
        ),
      )
      .optional(),
  }),
});

export const projectDemoReqSchema = z.object({
  projectId: z.string(),
  message: z.string().optional(),
});

export const projectDemoResSchema = z.object({
  projectInfo: z.object({
    id: z.string(),
    name: z.string(),
    shortName: z.string(),
    description: z.string().optional(),
  }),
});

export const deleteIntegrationReqSchema = z.object({
  projectId: z.string(),
  id: z.string(),
});

export const deleteIntegrationResSchema = z.object({
  success: z.boolean(),
  deletedId: z.string(),
});

export const getIntegrationsReqSchema = z.object({
  projectId: z.string().optional(),
  id: z.string().optional(),
  type: z
    .union([z.literal("GITLAB"), z.literal("GITHUB"), z.literal("MANUAL")])
    .optional(),
  enabled: z.boolean().optional(),
});

export const integrationConfigSchema = z.object({
  projectUrl: z.string().optional(),
  pipelineRef: z.string().optional(),
  token: z.string().optional(),
  webhookSecret: z.string().optional(),
});

export const integrationItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.union([
    z.literal("GITLAB"),
    z.literal("GITHUB"),
    z.literal("MANUAL"),
  ]),
  enabled: z.boolean(),
  config: integrationConfigSchema,
});

export const listIntegrationsResSchema = z.object({
  items: z.array(integrationItemSchema),
  total: z.number(),
});

export const createIntegrationReqSchema = z.object({
  projectId: z.string(),
  name: z.string(),
  type: z.union([
    z.literal("GITLAB"),
    z.literal("GITHUB"),
    z.literal("MANUAL"),
  ]),
  enabled: z.boolean(),
  config: z.object({
    projectUrl: z.string().optional(),
    pipelineRef: z.string().optional(),
    token: z.string().optional(),
    webhookSecret: z.string().optional(),
  }),
});

export const createIntegrationResSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.union([
    z.literal("GITLAB"),
    z.literal("GITHUB"),
    z.literal("MANUAL"),
  ]),
  enabled: z.boolean(),
  config: z.object({
    projectUrl: z.string().optional(),
    pipelineRef: z.string().optional(),
    token: z.string().optional(),
    webhookSecret: z.string().optional(),
  }),
});

export const updateIntegrationReqSchema = z.object({
  projectId: z.string(),
  id: z.string(),
  name: z.string().optional(),
  type: z
    .union([z.literal("GITLAB"), z.literal("GITHUB"), z.literal("MANUAL")])
    .optional(),
  enabled: z.boolean().optional(),
  config: z
    .object({
      projectUrl: z.string().optional(),
      pipelineRef: z.string().optional(),
      token: z.string().optional(),
      webhookSecret: z.string().optional(),
    })
    .optional(),
});

export const updateIntegrationResSchema = z.object({
  id: z.string(),
  name: z.string(),
  type: z.union([
    z.literal("GITLAB"),
    z.literal("GITHUB"),
    z.literal("MANUAL"),
  ]),
  enabled: z.boolean(),
  config: z.object({
    projectUrl: z.string().optional(),
    pipelineRef: z.string().optional(),
    token: z.string().optional(),
    webhookSecret: z.string().optional(),
  }),
});

export const settingsReqSchema = z.object({
  projectId: z.string(),
});

export const settingsResSchema = z.object({
  bugReportsProject: z.string().nullable(),
  testRunsProject: z.string().nullable(),
  testSuitFieldName: z.string().nullable(),
  bugIssueCommand: z.string().nullable(),
  customLinkType: z.string().nullable(),
  isTestCaseProject: z.boolean(),
});

export const getTestRunReqSchema = z.object({
  projectId: z.string().optional(),
  id: z.string().optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  suiteId: z.string().optional(),
  status: z.string().optional(),
  testCaseId: z.string().optional(),
});

export const getTestRunItemSchema = z.object({
  id: z.string(),
  testCaseIDs: z.array(z.string()),
  testSuiteID: z.string(),
  testSuiteName: z.string(),
  status: z.string(),
  executionTarget: z.object({
    id: z.string(),
    name: z.string(),
    type: z.string(),
    ref: z.string(),
  }),
});

export const listTestRunsResSchema = z.object({
  items: z.array(getTestRunItemSchema),
  total: z.number(),
});

export const createTestRunReqSchema = z.object({
  projectId: z.string(),
  suiteID: z.string(),
  testCaseIDs: z.array(z.string()),
  executionMode: z
    .union([z.literal("MANAGED"), z.literal("OBSERVED")])
    .optional(),
  executionTarget: z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      type: z
        .union([z.literal("GITLAB"), z.literal("GITHUB"), z.literal("MANUAL")])
        .optional(),
      ref: z.string().optional(),
    })
    .optional(),
});

export const createTestRunResSchema = z.object({
  id: z.string(),
  issueId: z.string(),
  testCaseIDs: z.array(z.string()),
  testSuiteID: z.string(),
  status: z.string(),
  executionTarget: z.object({
    id: z.string(),
    name: z.string(),
    type: z.string(),
    ref: z.string(),
  }),
});

export const deleteTestSuiteReqSchema = z.object({
  projectId: z.string(),
  id: z.string(),
});

export const deleteTestSuiteResSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const getTestSuiteReqSchema = z.object({
  projectId: z.string(),
  id: z.string().optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  search: z.string().optional(),
});

export const testSuiteItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  testCaseCount: z.number(),
});

export const getTestSuiteResSchema = z.object({
  items: z.array(testSuiteItemSchema),
  total: z.number(),
});

export const createTestSuiteReqSchema = z.object({
  projectId: z.string(),
  name: z.string(),
  description: z.string().optional(),
});

export const createTestSuiteResSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  testCaseIDs: z.array(z.string()),
});

export const updateTestSuiteReqSchema = z.object({
  projectId: z.string(),
  id: z.string(),
  name: z.string().optional(),
  description: z.string().optional(),
  testCaseIDs: z.array(z.string()).optional(),
});

export const updateTestSuiteResSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  testCaseIDs: z.array(z.string()),
});

export const getTestCaseReqSchema = z.object({
  projectId: z.string().optional(),
  id: z.string().optional(),
  limit: z.number().optional(),
  offset: z.number().optional(),
  search: z.string().optional(),
  suiteId: z.string().optional(),
});

export const testCaseItemSchema = z.object({
  id: z.string(),
  issueId: z.string().optional(),
  summary: z.string(),
  description: z.string(),
  suiteId: z.string().optional(),
});

export const getTestCaseResSchema = z.object({
  items: z.array(testCaseItemSchema),
  total: z.number(),
});

export const createTestCaseReqSchema = z.object({
  projectId: z.string(),
  summary: z.string(),
  description: z.string().optional(),
  suiteId: z.string().optional(),
});

export const createTestCaseResSchema = z.object({
  id: z.string(),
  issueId: z.string(),
  summary: z.string(),
  description: z.string(),
  suiteId: z.string().optional(),
});

export const updateTestCaseReqSchema = z.object({
  projectId: z.string(),
  id: z.string(),
  issueId: z.string().optional(),
  summary: z.string().optional(),
  description: z.string().optional(),
  suiteId: z.string().optional(),
});

export const updateTestCaseResSchema = z.object({
  id: z.string(),
  issueId: z.string().optional(),
  summary: z.string(),
  description: z.string(),
  suiteId: z.string().optional(),
});

export const gitLabWebhookReqSchema = z.object({});

export const gitLabWebhookResSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const testRunResultReqSchema = z.object({
  testRunID: z.string(),
  passed: z.boolean(),
});

export const testRunResultResSchema = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export const tMSQueryReqSchema = z.object({
  projectId: z.string().optional(),
  query: z.string(),
  entityType: z.union([
    z.literal("testCase"),
    z.literal("testRun"),
    z.literal("testSuite"),
  ]),
  extensionPropertiesQuery: z.record(z.unknown()).optional(),
});

export const tMSQueryResSchema = z.object({
  items: z.array(
    z.object({
      id: z.string(),
      idReadable: z.string().optional(),
      summary: z.string(),
      description: z.string().optional(),
      project: z
        .object({
          id: z.string(),
          name: z.string(),
        })
        .optional(),
    }),
  ),
});

// Nested schema object for validation system
export const schema = {
  global: {
    demo: {
      GET: {
        Res: healthCheckResSchema
      }
    },
    testCaseProject: {
      GET: {
        Res: testCaseProjectsResSchema
      }
    },
    settings: {
      GET: {
        Res: appSettingsResSchema
      }
    },
    webhooks: {
      gitlab: {
        POST: {
          Req: gitLabWebhookReqSchema,
          Res: gitLabWebhookResSchema
        }
      }
    }
  },
  project: {
    demo: {
      GET: {
        Req: projectDemoReqSchema,
        Res: projectDemoResSchema
      }
    },
    integrations: {
      DELETE: {
        Req: deleteIntegrationReqSchema,
        Res: deleteIntegrationResSchema
      },
      GET: {
        Req: getIntegrationsReqSchema,
        Res: listIntegrationsResSchema
      },
      POST: {
        Req: createIntegrationReqSchema,
        Res: createIntegrationResSchema
      },
      PUT: {
        Req: updateIntegrationReqSchema,
        Res: updateIntegrationResSchema
      }
    },
    settings: {
      GET: {
        Req: settingsReqSchema,
        Res: settingsResSchema
      }
    },
    testRuns: {
      GET: {
        Req: getTestRunReqSchema,
        Res: listTestRunsResSchema
      },
      POST: {
        Req: createTestRunReqSchema,
        Res: createTestRunResSchema
      },
      results: {
        POST: {
          Req: testRunResultReqSchema,
          Res: testRunResultResSchema
        }
      }
    },
    testSuites: {
      DELETE: {
        Req: deleteTestSuiteReqSchema,
        Res: deleteTestSuiteResSchema
      },
      GET: {
        Req: getTestSuiteReqSchema,
        Res: getTestSuiteResSchema
      },
      POST: {
        Req: createTestSuiteReqSchema,
        Res: createTestSuiteResSchema
      },
      PUT: {
        Req: updateTestSuiteReqSchema,
        Res: updateTestSuiteResSchema
      }
    },
    testCases: {
      GET: {
        Req: getTestCaseReqSchema,
        Res: getTestCaseResSchema
      },
      POST: {
        Req: createTestCaseReqSchema,
        Res: createTestCaseResSchema
      },
      PUT: {
        Req: updateTestCaseReqSchema,
        Res: updateTestCaseResSchema
      }
    },
    tms: {
      query: {
        POST: {
          Req: tMSQueryReqSchema,
          Res: tMSQueryResSchema
        }
      }
    }
  }
};
